# Generated by Django 3.0 on 2020-03-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200310_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_registration',
            name='eveningtime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_registration',
            name='fees',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_registration',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='doctor_registration',
            name='morningtime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_registration',
            name='workingdays',
            field=models.CharField(max_length=200),
        ),
    ]
