# Generated by Django 3.0 on 2020-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200311_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_registration',
            name='eveningtime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
