# Generated by Django 3.0 on 2020-03-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200311_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_registration',
            name='eveningtime',
        ),
        migrations.RemoveField(
            model_name='doctor_registration',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='doctor_registration',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctor_registration',
            name='morningtime',
        ),
        migrations.RemoveField(
            model_name='doctor_registration',
            name='workingdays',
        ),
    ]
