# Generated by Django 3.0 on 2020-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200311_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='eveningtime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_registration',
            name='fees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor_registration',
            name='image',
            field=models.ImageField(default='', max_length=1000, upload_to='images'),
        ),
        migrations.AddField(
            model_name='doctor_registration',
            name='morningtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor_registration',
            name='workingdays',
            field=models.CharField(default='', max_length=200),
        ),
    ]
