# Generated by Django 3.0 on 2020-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor_registration',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
