# Generated by Django 3.0 on 2020-03-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
