# Generated by Django 3.0 on 2020-03-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='pharmacy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Pharmacy_registration'),
        ),
    ]
