# Generated by Django 3.0 on 2020-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
