# Generated by Django 3.0 on 2020-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_patient_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.CharField(default='true', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
