# Generated by Django 3.0 on 2020-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200321_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='servicename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
