# Generated by Django 3.0 on 2020-04-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200413_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='servicename',
            new_name='reportname',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
    ]
