# Generated by Django 3.0 on 2020-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200415_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='reportdetail1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='time',
            new_name='reportdetail2',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='message',
            new_name='reportdetail3',
        ),
        migrations.AddField(
            model_name='report',
            name='reportdetail4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='reportdetail5',
            field=models.CharField(default='', max_length=300),
        ),
    ]
