# Generated by Django 3.0 on 2020-04-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_reportbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbooking',
            name='reports',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Report'),
        ),
    ]
