# Generated by Django 3.0 on 2020-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_reportbooking_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
