# Generated by Django 3.0 on 2020-04-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_reportbooking_servicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbooking',
            name='reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Report'),
        ),
    ]
